name: Publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch:
    inputs:
      level:
        description: "Release level"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build
        run: |
          GOOS=darwin GOARCH=amd64 go build -o package/dist/darwin/amd64/aux4-search .
          GOOS=darwin GOARCH=arm64 go build -o package/dist/darwin/arm64/aux4-search .
          GOOS=linux GOARCH=amd64 go build -o package/dist/linux/amd64/aux4-search .
          GOOS=linux GOARCH=arm64 go build -o package/dist/linux/arm64/aux4-search .
          GOOS=linux GOARCH=386 go build -o package/dist/linux/386/aux4-search .
          GOOS=windows GOARCH=amd64 go build -o package/dist/windows/amd64/aux4-search.exe .
          GOOS=windows GOARCH=arm64 go build -o package/dist/windows/arm64/aux4-search.exe .
          GOOS=windows GOARCH=386 go build -o package/dist/windows/386/aux4-search.exe .

      - name: Test
        run: |
          go build -o package/aux4-search .
          cd package && aux4 test run

      - name: Publish
        uses: aux4/publish-package-action@v1
        with:
          level: ${{ github.event.inputs.level || 'patch' }}
          aux4_token: ${{ secrets.AUX4_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
